# Generated by Django 4.0.3 on 2022-03-25 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('code', models.CharField(db_index=True, default=games.models.generate_random_code, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('running', 'Running'), ('finished', 'Finished')], default='draft', max_length=8)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, games.models.DatetimeMixin),
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            bases=(models.Model, games.models.DatetimeMixin),
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, games.models.DatetimeMixin),
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            bases=(models.Model, games.models.DatetimeMixin),
        ),
        migrations.CreateModel(
            name='PlayerRoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_voted', models.BooleanField(default=False)),
                ('answer_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_1', to='games.gameplayer')),
                ('answer_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_2', to='games.gameplayer')),
                ('answer_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_3', to='games.gameplayer')),
                ('game_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameround')),
            ],
            bases=(models.Model, games.models.DatetimeMixin),
        ),
        migrations.CreateModel(
            name='PlayerFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamecategory')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameplayer')),
            ],
            bases=(models.Model, games.models.DatetimeMixin),
        ),
        migrations.AddField(
            model_name='gameround',
            name='player_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.playerfact'),
        ),
    ]
